// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsysJJWO-G-Gkw-2J58i25dNhGtucKROI',
    appId: '1:878600121764:web:565bec2207ddcc6c996531',
    messagingSenderId: '878600121764',
    projectId: 'hicom-ops',
    authDomain: 'hicom-ops.firebaseapp.com',
    storageBucket: 'hicom-ops.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHgTOiKbgQbpaT9TqoJpPvZ-2ltyaIlgw',
    appId: '1:878600121764:android:945678bada04583f996531',
    messagingSenderId: '878600121764',
    projectId: 'hicom-ops',
    storageBucket: 'hicom-ops.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2hOZt8_bbSprSQRAqxDmoEl0GGuLgfl4',
    appId: '1:878600121764:ios:8677dd04d84d128e996531',
    messagingSenderId: '878600121764',
    projectId: 'hicom-ops',
    storageBucket: 'hicom-ops.firebasestorage.app',
    iosBundleId: 'com.hicom.hicomOps',
  );
}
